# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-Translate-InterTran
version:      0.01
version_from: lib/Lingua/Translate/InterTran.pm
installdirs:  site
license:      perl
requires:
    Lingua::Translate:             0.08
    LWP::UserAgent:                0
    Test::More:                    0
    URI:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
